// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWord(arg1) {
  return window['go']['main']['App']['CreateWord'](arg1);
}

export function DeleteWord(arg1) {
  return window['go']['main']['App']['DeleteWord'](arg1);
}

export function GetWord(arg1) {
  return window['go']['main']['App']['GetWord'](arg1);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function SearchWords(arg1, arg2) {
  return window['go']['main']['App']['SearchWords'](arg1, arg2);
}

export function UpdateWord(arg1, arg2) {
  return window['go']['main']['App']['UpdateWord'](arg1, arg2);
}
