// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dictionary} from '../models';

export function CreateWord(arg1:dictionary.WordInput):Promise<number>;

export function DeleteWord(arg1:number):Promise<void>;

export function GetWord(arg1:number):Promise<dictionary.Word>;

export function ListCategories():Promise<Array<dictionary.Category>>;

export function SearchWords(arg1:string,arg2:string):Promise<Array<dictionary.Word>>;

export function UpdateWord(arg1:number,arg2:dictionary.WordInput):Promise<void>;
